"""add_description

Revision ID: 15c277a4d2c9
Revises: 5d59bfdb266f
Create Date: 2022-07-28 18:57:35.492680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c277a4d2c9'
down_revision = '5d59bfdb266f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flat', 'description')
    # ### end Alembic commands ###
