"""add history_of_price

Revision ID: 344ec8c36ff7
Revises: c55ce72e0387
Create Date: 2022-08-07 11:22:42.343264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344ec8c36ff7'
down_revision = 'c55ce72e0387'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_of_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('time_of_price', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_of_price')
    # ### end Alembic commands ###
