"""corrections

Revision ID: 49f02662e669
Revises: ac52eec412e4
Create Date: 2022-07-30 16:56:37.938459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f02662e669'
down_revision = 'ac52eec412e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('floors_in_the_house', sa.Integer(), nullable=True))
    op.drop_column('house', 'floors_in_the_hourse')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('floors_in_the_hourse', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('house', 'floors_in_the_house')
    # ### end Alembic commands ###
