"""add_status_warm_floor

Revision ID: 5d59bfdb266f
Revises: 241f26cd32dd
Create Date: 2022-07-27 21:27:09.874848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d59bfdb266f'
down_revision = '241f26cd32dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('warm_floor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flat', 'warm_floor')
    # ### end Alembic commands ###
