"""start

Revision ID: 640bd05101e7
Revises: 
Create Date: 2022-08-15 08:30:49.080215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640bd05101e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller', sa.String(length=120), nullable=True),
    sa.Column('type_seller', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=155), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('district',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obl', sa.String(length=155), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sailing_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('street',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street', sa.String(length=155), nullable=False),
    sa.Column('number_of_house', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('where_download',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('new_building_name', sa.String(length=200), nullable=True),
    sa.Column('offical_builder', sa.String(length=200), nullable=True),
    sa.Column('year_of_construction', sa.Integer(), nullable=True),
    sa.Column('floors_in_the_house', sa.Integer(), nullable=True),
    sa.Column('type_of_home', sa.String(length=150), nullable=True),
    sa.Column('passenger_bodice', sa.String(length=100), nullable=True),
    sa.Column('service_lift', sa.String(length=100), nullable=True),
    sa.Column('in_home', sa.String(length=200), nullable=True),
    sa.Column('yard', sa.Text(), nullable=True),
    sa.Column('parking', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(length=150), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_avito', sa.BIGINT(), nullable=True),
    sa.Column('number_of_tel', sa.String(length=120), nullable=True),
    sa.Column('price', sa.BIGINT(), nullable=False),
    sa.Column('qty_of_rooms', sa.String(length=50), nullable=False),
    sa.Column('total_space', sa.DECIMAL(), nullable=False),
    sa.Column('square_of_kitchen', sa.DECIMAL(), nullable=True),
    sa.Column('living_space', sa.DECIMAL(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('furniture', sa.String(length=200), nullable=True),
    sa.Column('technics', sa.String(length=200), nullable=True),
    sa.Column('balcony_or_loggia', sa.String(length=120), nullable=True),
    sa.Column('room_type', sa.String(length=120), nullable=True),
    sa.Column('ceiling_height', sa.DECIMAL(), nullable=True),
    sa.Column('bathroom', sa.String(length=120), nullable=True),
    sa.Column('window', sa.String(length=120), nullable=True),
    sa.Column('repair', sa.String(length=120), nullable=True),
    sa.Column('seilling_method', sa.String(length=120), nullable=True),
    sa.Column('transaction_type', sa.String(length=120), nullable=True),
    sa.Column('decorating', sa.String(length=120), nullable=True),
    sa.Column('warm_floor', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('time_of_add', sa.TIMESTAMP(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_of_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.BIGINT(), nullable=False),
    sa.Column('time_of_add_price', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obl_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['flat_id'], ['flat.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['obl_id'], ['obl.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sailing_status.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['sailing_status.id'], ),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_flat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rel', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rel'], ['relations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['where_download.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_flat')
    op.drop_table('relations')
    op.drop_table('history_of_price')
    op.drop_table('flat')
    op.drop_table('house')
    op.drop_table('where_download')
    op.drop_table('street')
    op.drop_table('sailing_status')
    op.drop_table('obl')
    op.drop_table('district')
    op.drop_table('city')
    op.drop_table('author')
    # ### end Alembic commands ###
