"""add FK site_id

Revision ID: a04ddc05809b
Revises: b43a9b3b073e
Create Date: 2022-08-06 11:32:22.257084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04ddc05809b'
down_revision = 'b43a9b3b073e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('site_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'relations', 'sailing_status', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.drop_column('relations', 'site_id')
    # ### end Alembic commands ###
