"""corrections

Revision ID: ac52eec412e4
Revises: 15c277a4d2c9
Create Date: 2022-07-30 16:55:13.207948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac52eec412e4'
down_revision = '15c277a4d2c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('city', sa.String(length=150), nullable=True))
    op.add_column('house', sa.Column('type_of_home', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'type_of_home')
    op.drop_column('house', 'city')
    # ### end Alembic commands ###
