"""change table Rel

Revision ID: b43a9b3b073e
Revises: 70c87aca4d2f
Create Date: 2022-08-06 11:19:14.976542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43a9b3b073e'
down_revision = '70c87aca4d2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
