"""add url

Revision ID: bee5b0683759
Revises: febfe04a1388
Create Date: 2022-08-15 06:30:59.372021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee5b0683759'
down_revision = 'febfe04a1388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('url', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flat', 'url')
    # ### end Alembic commands ###
