"""add price

Revision ID: cf8df114e8c6
Revises: 344ec8c36ff7
Create Date: 2022-08-07 12:19:00.745619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf8df114e8c6'
down_revision = '344ec8c36ff7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_of_price', sa.Column('price', sa.BIGINT(), nullable=False))
    op.add_column('history_of_price', sa.Column('time_of_add_price', sa.TIMESTAMP(), nullable=False))
    op.drop_column('history_of_price', 'time_of_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_of_price', sa.Column('time_of_price', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('history_of_price', 'time_of_add_price')
    op.drop_column('history_of_price', 'price')
    # ### end Alembic commands ###
