"""add_status

Revision ID: e0de2d2f283d
Revises: 602f06b20ec8
Create Date: 2022-07-25 06:40:30.085156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0de2d2f283d'
down_revision = '602f06b20ec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('where_download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_author', sa.Integer(), nullable=True),
    sa.Column('id_in_site', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['where_download.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('district', 'name_area',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('flat', sa.Column('time_of_add', sa.TIMESTAMP(), nullable=False))
    op.add_column('flat', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('flat', sa.Column('site_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'flat', 'where_download', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flat', type_='foreignkey')
    op.drop_column('flat', 'site_id')
    op.drop_column('flat', 'status')
    op.drop_column('flat', 'time_of_add')
    op.alter_column('district', 'name_area',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('active_flat')
    op.drop_table('where_download')
    # ### end Alembic commands ###
