"""add model obl and city

Revision ID: ec1a3aeb8830
Revises: 2a0f5ca1483d
Create Date: 2022-08-03 19:58:31.110204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1a3aeb8830'
down_revision = '2a0f5ca1483d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obl', sa.String(length=155), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=155), nullable=False),
    sa.Column('obl_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['obl_id'], ['obl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('district', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'district', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'district', type_='foreignkey')
    op.drop_column('district', 'city_id')
    op.drop_table('city')
    op.drop_table('obl')
    # ### end Alembic commands ###
