"""add

Revision ID: febfe04a1388
Revises: 0c01a74d89f8
Create Date: 2022-08-14 22:06:57.363915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febfe04a1388'
down_revision = '0c01a74d89f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
